Drop support for Shoots with Kubernetes version <= 1.26
gardener/gardener-extension-shoot-lakom-service pull request #118
Opened 2024-10-31 06:51 UTC by RadaBDimitrova

**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
- Adapt PDBs to use unhealthyPodEvictionPolicy: AlwaysAllow unconditionally
- Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.26.
- Adapt service.kubernetes.io/topology-mode annotation

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/10339

**Special notes for your reviewer**:
In draft until the gardener/gardener PR is merged and released.

**Release note**:

```other operator
`extension-shoot-lakom-service` no longer supports Shoots with Кubernetes version <= 1.26.
```

2024-11-01 16:27 UTC, vpnachev reviewed
Thanks you for the changes!
I have some suggestions in-line.

2024-11-01 16:27 UTC, vpnachev commented on pkg/controller/lifecycle/actuator_test.go
> +			Entry("Kubernetes version >= 1.27", semver.MustParse("1.27.0"), true, false, false, false),
The `k8sVersion` parameter is becoming obsolete, it was used just to generated different pod disruption budgets depending on whether the k8s version `<= v1.26` or not.

For completeness, you can also drop the `k8sVersion` parameter from the `getSeedResources` function here:
- https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/9ee7121684091d71148300c087a2341c929cb111/pkg/controller/lifecycle/actuator.go#L290

Then the PDB can be changed to always set `unhealthyPodEvictionPolicy=AlwaysAllow` here
- https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/9ee7121684091d71148300c087a2341c929cb111/pkg/controller/lifecycle/actuator.go#L496-L508


`expectedSeedPDB` can be also simplified as now it is always the same
- https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/9ee7121684091d71148300c087a2341c929cb111/pkg/controller/lifecycle/actuator_test.go#L560-L587

2025-03-05 10:22 UTC, ialidzhikov requested changes

2025-03-05 10:22 UTC, ialidzhikov commented on charts/gardener-extension-shoot-lakom-service/templates/poddisruptionbudget.yaml
> +  unhealthyPodEvictionPolicy: AlwaysAllow
You could preserve the existing empty line at the end of the file.

2025-03-05 10:22 UTC, ialidzhikov commented on charts/lakom/charts/runtime/templates/poddisruptionbudget.yaml
> +  unhealthyPodEvictionPolicy: AlwaysAllow
You could preserve the existing empty line at the end of the file.

2025-03-05 10:22 UTC, ialidzhikov commented on charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/poddisruptionbudget.yaml
> +  unhealthyPodEvictionPolicy: AlwaysAllow
You could preserve the existing empty line at the end of the file.

2025-03-05 10:22 UTC, ialidzhikov commented on pkg/controller/seed/reconciler_test.go
> +			Entry("Kubernetes version >= 1.27", "1.27.0", true, false, false, false),
You have to:
- adapt https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/7bc4882adb4585e0ed82397592f58e197cb94c8a/pkg/controller/seed/reconciler.go#L413-L425
- remove the `k8sVersion` at https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/7bc4882adb4585e0ed82397592f58e197cb94c8a/pkg/controller/seed/reconciler.go#L188
- remove https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/086059d37dcd6ad7a5f84e9bd199fff3604bd17e/pkg/controller/seed/reconciler_test.go#L49
- adapt https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/086059d37dcd6ad7a5f84e9bd199fff3604bd17e/pkg/controller/seed/reconciler_test.go#L114-L115

2025-03-06 12:17 UTC, ialidzhikov requested changes

2025-03-11 15:07 UTC, ialidzhikov approved these changes
/lgtm

Thanks!

2025-03-11 15:08 UTC, ialidzhikov commented
/invite @gardener/lakom-maintainers 
for approval

2025-03-11 15:12 UTC, dimityrmirchev approved these changes
/lgtm

2025-03-11 15:12 UTC, merged